version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 16.18.1
  pre_build:
    commands:
      - echo "preBuild APP"
      - rm -rf node_modules **/node_modules
      - npm cache clean --force
      - yarn cache clean
      - yarn install --frozen-lockfile
      - yarn global add next@12.0.7
  build:
    commands:
      - NEXT_PUBLIC_GQ_URL=${NEXT_PUBLIC_GQ_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_AWS_API_GATEWAY=${NEXT_PUBLIC_AWS_API_GATEWAY}
      - NEXT_PUBLIC_GQ_SCHEMA_URL=${NEXT_PUBLIC_GQ_SCHEMA_URL}
      - NEXT_PUBLIC_UPDATING_SITE=${NEXT_PUBLIC_UPDATING_SITE}
      - NEXT_PUBLIC_DEVELOPMENT_MODE=${NEXT_PUBLIC_DEVELOPMENT_MODE}
      - NEXT_PUBLIC_PATHNAME_PREFIX=${NEXT_PUBLIC_PATHNAME_PREFIX}
      - NEXT_PUBLIC_SEA_PORT=${NEXT_PUBLIC_SEA_PORT}
      - NEXT_PUBLIC_QUICKNODE_API_KEY=${NEXT_PUBLIC_QUICKNODE_API_KEY}
      - NEXT_PUBLIC_METAPLEX_AUCTION_HOUSE_GAME_TRADE_MARKET=${NEXT_PUBLIC_METAPLEX_AUCTION_HOUSE_GAME_TRADE_MARKET}
      - WORK_MODE=${WORK_MODE}
      - echo "Build APP"
      - pwd
      - ./cli.sh deploy_app
      - ./cli.sh remove_modules
      - rm -rf .next/cache
artifacts:
  files:
    - '**/*'
discard-paths: no
cache:
  paths:
    - node_modules/**/*
